apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-prometheus-exporter
  labels:
    app: nginx-prometheus-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-prometheus-exporter
  template:
    metadata:
      labels:
        app: nginx-prometheus-exporter
    spec:
      containers:
        - name: nginx-prometheus-exporter
          image: nginx/nginx-prometheus-exporter:0.4.2
          ports:
            - containerPort: 9113
          args:
            - --nginx.scrape-uri=http://133.186.221.98/metrics
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-prometheus-exporter
spec:
  selector:
    app: nginx-prometheus-exporter
  ports:
    - protocol: TCP
      port: 9113
      targetPort: 9113
