apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: luckyjakey/nginx:latest # 사용할 커스텀 Nginx 이미지
          ports:
            - containerPort: 80
